### PR TITLE
Fix possible collision in session tickets by increasing the randomness of ticket generation

### PR DESCRIPTION
**Pull request by racerpeter**

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Let me know when you're done making changes here and I'll take a look. I don't think the Travis failures are due to what you did.

**Comment by JasonBarnabe** [comment]
@racerpeter I would like to include this but I'm getting test failures (on all tests):

```
 77) Error:
RoutesTest#test_qwc:
ActiveRecord::StatementInvalid: SQLite3::ReadOnlyException: attempt to write a readonly database: DELETE FROM "qbwc_jobs"
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/sqlite3-1.3.10/lib/sqlite3/statement.rb:108:in `step'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/sqlite3-1.3.10/lib/sqlite3/statement.rb:108:in `block in each'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/sqlite3-1.3.10/lib/sqlite3/statement.rb:107:in `loop'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/sqlite3-1.3.10/lib/sqlite3/statement.rb:107:in `each'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activerecord-4.2.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:303:in `to_a'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activerecord-4.2.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:303:in `block in exec_query'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activerecord-4.2.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:297:in `exec_query'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activerecord-4.2.0/lib/active_record/connection_adapters/sqlite3_adapter.rb:323:in `exec_delete'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:119:in `delete'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activerecord-4.2.0/lib/active_record/relation.rb:477:in `delete_all'
    /home/jason/.rvm/gems/ruby-2.3.1@qbwc/gems/activerecord-4.2.0/lib/active_record/querying.rb:8:in `delete_all'
    /www/qbwc/lib/qbwc/active_record/job.rb:134:in `clear_jobs'
    /www/qbwc/lib/qbwc.rb:133:in `clear_jobs'
    /www/qbwc/test/qbwc/integration/routes_test.rb:17:in `setup'
```

**Comment by racerpeter** [comment]
@JasonBarnabe It looks like that error is related to ruby not having the right file permissions on the temporary sqlite file that is created for tests. I switched to a file for sqlite vs memory, which is required to make the multi-threaded regression spec work.

Can you try setting the TEST_SQLITE_DB env to something writeable in your travis configuration?

**Comment by JasonBarnabe** [comment]
I got that locally, not on Travis. The problem seems to be that the tempfile is deleted before the test is over. Maintaining a reference to it seems to solve the problem:

```ruby
db_path = ENV["TEST_SQLITE_DB"] || (@tempfile = Tempfile.new("sqlite-qb")).path
```

**Comment by JasonBarnabe** [comment]
If this gets fixed up to work I would gladly use, but it's not usable as is.

**Pull request closed without merging**
