### PR TITLE
Changes discussed in Issue #79

### PR DESCRIPTION
**Pull request by bkroeker**
* Passed in session and data variables to workers to allow for greater control over when jobs are run, and how to generate requests.
* Added some database indexes to improve DB interaction speed.
* Added a callback for code to run when a session has successfully completed all jobs.
* Exposed the session's created_at time via QBWC::Session#began_at.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
This is good, but

1. Fix the broken tests
2. Add some new tests
3. Update the documentation to include the additional parameters and the new session completion proc

Thanks!

**Comment by bkroeker** [comment]
Yeah, fair enough.  It'll take me a while to fix the tests though, so we'll just have to wait I guess.  I have other priorities in life at the moment. :(

**Comment by JasonBarnabe** [comment]
Fixing the tests should just be a matter of adding the extra parameters to the existing test workers.

**Comment by bkroeker** [comment]
Yes, but most of the failing tests don't have readily available parameters to pass in.  Like the session, for example.  It wasn't immediately obvious to me how to create a session in the tests and pass it through properly.  I tried looking for examples I could copy from, but I didn't see any that quite worked.  I'd have to study the test structure a bit more in order to understand what's going on and how best to fix everything.  And I just don't have time at the moment.

**Comment by JasonBarnabe** [comment]
Right, you would need a real-ish session to test the new functionality, but since the existing tests don't use the session anyway, all that would be needed would be to change their signatures to accept a session.

**Comment by bkroeker** [comment]
Fixed, finally!

**Comment by JasonBarnabe** [comment]
1. ~~Fix the broken tests~~
2. Add some new tests
3. Update the documentation to include the additional parameters and the new session completion proc

**Comment by bkroeker** [comment]
So the first test I wrote revealed a bug with the gem in which sessions contaminated each other.

```ruby
  class ConditionalTestWorker < QBWC::Worker
    def requests(job, session, data)
      {:customer_query_rq => {:full_name => session.user}}
    end
  end

  test "stuff" do
    timothy_session  = QBWC::Session.new("timothy", COMPANY)
    susan_session    = QBWC::Session.new("susan", COMPANY)

    # Simulate requests
    timothy_request = timothy_session.current_request
    assert timothy_request.request.include?("timothy")
    timothy_session.response = QBWC_CUSTOMER_QUERY_RESPONSE_INFO
    assert_equal 100, timothy_session.progress

    susan_request = susan_session.current_request
    assert susan_request.request.include?("susan")  # ***
    susan_session.response = QBWC_CUSTOMER_QUERY_RESPONSE_INFO
    assert_equal 100, susan_session.progress
  end
```

The `***` assertion failed, since susan_request.request was returning `{:customer_query_rq => {:full_name => "timothy"}}`.  I had to do quite a bit of hacking to isolate requests so that different sessions could have different requests for the same job.  I think it worked out in the end though.

In any case, you now have some new tests, and documentation for the features I added.

**Comment by JasonBarnabe** [comment]
Great! Thanks!

**Pull request merged**
