### PR TITLE
Make compatible with rails 5.1, drop rails 4

### PR DESCRIPTION
**Pull request by lostapathy**
This started with adding a rails-5.1 appraisal and bumping ruby versions to latest but quickly expanded.

Starting with rails-5.1, all migrations must be versioned.  Adding versions to the migrations breaks rails 4.x compatibility.  Normally this is fairly straightforward to deal with because the migration templates are templates, and the templates can be updated to generate appropriate code for the rails version in use - see https://github.com/thoughtbot/clearance/commit/b0ce189c69d52155660232604cc30d729d6b4221

The specs for qbwc require the templates directly (see: https://github.com/qbwc/qbwc/blob/master/test/test_helper.rb#L56) so the technique used above doesn't apply.  That leaves us with the choice of either rewriting the specs or dropping rails-4 compatibility going forward.  I opted to drop rails-4 support since that's the much simpler answer, and rails 4.2 is no longer supported.  If that's a blocker for merging this PR, I can work on updating the specs instead.

~~This is not yet ready to merge because wash_out 0.12.0 has not yet been released, but I have tested it with wash_out directly from github in my Gemfile and it works fine.  I wanted to get this published to get feedback on rails 4.1 support vs rewriting the specs.  Thanks!~~

### CODE REVIEW

**Comment by lostapathy** [comment]
I also removed gemfiles/*.lock from git as, per Appraisal docs, those should not be committed.  I believe that was resulting in build issues as seen on #116

**Comment by lostapathy** [comment]
wash_out 0.12.0 has been released, so this should be ready to go now.

If something needs changed so this can be merged please let me know, but it'd be great to get this merged and a new gem version cut so this gem is rails-5.1 compatible.  Thanks!

**Comment by JasonBarnabe** [comment]
I am unlikely to work on my app that uses qbwc in the near future, so I won't be able to test this. Can you (or anyone else) confirm that things look good in Rails 5.1 with this change?

Reviewing the code:

- Why GitHub for wash_out instead of RubyGems?
- Update qbwc.gemspec for the new minimum Rails requirement.
- Remove the action_view requirement in qbwc.gemspec as I believe that is now fixed in wash_out - https://github.com/inossidabile/wash_out/pull/223

**Comment by lostapathy** [comment]
I can confirm that, yes, this does seem to work fine on rails 5.1.  We still aren't full production with our integration, but I've tested it pretty heavily without any issues.

* The references to github under gemfiles/ are a mistake, good catch.  I originally pointed the gemfile at github for testing until wash_out 0.12.0 was released, but forgot to run appraisal to regenerate those gemfiles.  That should be corrected.
* Updated rails minimum version to 5.0.1 (seems common to use 5.0.1 vs 5.0.0 due to some early 5.0 issues)
* Good catch on the actionview dep, I removed that as well.

I did not bump the version in the gemspec, I'll leave that to your discretion.

Thanks for taking care of this gem, it's been a huge help for me.  We're pretty chained to Quickbooks, so I'll need this gem for a long time. If you'd like maintainer help let me know, I'd be glad to help.

**Pull request merged**
